### ISSUE TITLE
Clear access and refresh tokens if refresh fails

### ISSUE THREAD

**Issue by felixjendrusch** [rheinfabrik/Heimdall.swift#39]

**Comment by tibr** [comment]
I think we'd have to differentiate between the different failure reasons. Failure because a server or network error does not mean that the refresh token is not valid anymore.

To which errors should we react by clearing the token? Example: if the server responds with `unauthorized_client`, do we really want to wipe the token so that the user has to log in again? Maybe it's just temporary. As long as we're not 100% sure that the refresh token will not work later I'd leave the decision to the library user. We could offer a `clearToken` method for convenience.

**Comment by felixjendrusch** [comment]
Since refreshing is performed by the library itself, we should take care of handling errors relevant to that, like `invalid_grant`. See also #40.

**Comment by tibr** [comment]
Agreed, let's create issues for each relevant error and one for the token clearing function.

**Comment by felixjendrusch** [comment]
@haynzz @tibr is there any error among `invalid_request`, `invalid_client`, `invalid_grant`, `unauthorized_client`, `unsupported_grant_type` and `invalid_scope` that should not result in clearing the access and refresh tokens? See https://tools.ietf.org/html/rfc6749#section-5.2 for an explanation of the errors.

IMO, all of those should require requesting a new access token. Network errors should be passed on to the user.

**Comment by tibr** [comment]
I agree, they all sound pretty bad.

**Comment by haynzz** [comment]
I agre, too. As long as these errors only occur during login/authentication or token refresh, the only thing we can do is log the user out and show her the login screen with a message why she was logged out.
